<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="16" total="30" passed="8" failed="6" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-09T13:22:09 PDT" name="Suite" finished-at="2022-05-09T13:24:01 PDT" duration-ms="111670">
    <groups>
    </groups>
    <test started-at="2022-05-09T13:22:09 PDT" name="TestonChrome" finished-at="2022-05-09T13:23:17 PDT" duration-ms="68056">
      <class name="com.DsAlgoProject.TestCases.TC05_Stacks">
        <test-method signature="StacksTest()[pri:0, instance:com.DsAlgoProject.TestCases.TC05_Stacks@14b7786]" started-at="2022-05-09T13:23:09 PDT" name="StacksTest" finished-at="2022-05-09T13:23:16 PDT" duration-ms="7162" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- StacksTest -->
      </class> <!-- com.DsAlgoProject.TestCases.TC05_Stacks -->
      <class name="com.DsAlgoProject.TestCases.TC02_SignIn">
        <test-method signature="SignInTest(java.lang.String,java.lang.String)[pri:0, instance:com.DsAlgoProject.TestCases.TC02_SignIn@3f702946]" started-at="2022-05-09T13:22:38 PDT" name="SignInTest" data-provider="loginData" finished-at="2022-05-09T13:22:41 PDT" duration-ms="2791" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Neeshuindia]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Neeshu1234]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SignInTest -->
        <test-method signature="SignInTest(java.lang.String,java.lang.String)[pri:0, instance:com.DsAlgoProject.TestCases.TC02_SignIn@3f702946]" started-at="2022-05-09T13:22:41 PDT" name="SignInTest" data-provider="loginData" finished-at="2022-05-09T13:22:43 PDT" duration-ms="1746" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[neeshu]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Neeshu1234]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [NumpyNinja] but found [Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [NumpyNinja] but found [Login]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.DsAlgoProject.TestCases.TC02_SignIn.SignInTest(TC02_SignIn.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SignInTest -->
      </class> <!-- com.DsAlgoProject.TestCases.TC02_SignIn -->
      <class name="com.DsAlgoProject.TestCases.TC03_DataStructures">
        <test-method signature="DataStructuresTest()[pri:0, instance:com.DsAlgoProject.TestCases.TC03_DataStructures@42b6d0cc]" started-at="2022-05-09T13:22:44 PDT" name="DataStructuresTest" finished-at="2022-05-09T13:22:52 PDT" duration-ms="7862" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DataStructuresTest -->
      </class> <!-- com.DsAlgoProject.TestCases.TC03_DataStructures -->
      <class name="com.DsAlgoProject.TestCases.TC01_Registration">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.DsAlgoProject.TestCases.TC01_Registration@7dd611c8]" started-at="2022-05-09T13:22:10 PDT" name="setup" finished-at="2022-05-09T13:22:26 PDT" duration-ms="15129" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Registration(java.lang.String,java.lang.String)[pri:0, instance:com.DsAlgoProject.TestCases.TC01_Registration@7dd611c8]" started-at="2022-05-09T13:22:30 PDT" name="Registration" data-provider="loginData" finished-at="2022-05-09T13:22:33 PDT" duration-ms="2587" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Neeshuindia]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Neeshu1234]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [NumpyNinja] but found [Registration]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [NumpyNinja] but found [Registration]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.DsAlgoProject.TestCases.TC01_Registration.Registration(TC01_Registration.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Registration -->
        <test-method signature="Registration(java.lang.String,java.lang.String)[pri:0, instance:com.DsAlgoProject.TestCases.TC01_Registration@7dd611c8]" started-at="2022-05-09T13:22:35 PDT" name="Registration" data-provider="loginData" finished-at="2022-05-09T13:22:37 PDT" duration-ms="1736" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[neeshu]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Neeshu1234]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [NumpyNinja] but found [Registration]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [NumpyNinja] but found [Registration]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.DsAlgoProject.TestCases.TC01_Registration.Registration(TC01_Registration.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Registration -->
        <test-method is-config="true" signature="tearDown(java.lang.String)[pri:0, instance:com.DsAlgoProject.TestCases.TC01_Registration@7dd611c8]" started-at="2022-05-09T13:23:17 PDT" name="tearDown" finished-at="2022-05-09T13:23:17 PDT" duration-ms="843" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.DsAlgoProject.TestCases.TC01_Registration -->
      <class name="com.DsAlgoProject.TestCases.TC04_Arrays">
        <test-method signature="ArraysTest()[pri:0, instance:com.DsAlgoProject.TestCases.TC04_Arrays@1000d54d]" started-at="2022-05-09T13:22:52 PDT" name="ArraysTest" finished-at="2022-05-09T13:23:09 PDT" duration-ms="17141" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArraysTest -->
      </class> <!-- com.DsAlgoProject.TestCases.TC04_Arrays -->
    </test> <!-- TestonChrome -->
    <test started-at="2022-05-09T13:23:18 PDT" name="TestonEdge" finished-at="2022-05-09T13:24:01 PDT" duration-ms="42676">
      <class name="com.DsAlgoProject.TestCases.TC05_Stacks">
        <test-method signature="StacksTest()[pri:0, instance:com.DsAlgoProject.TestCases.TC05_Stacks@397ef2]" started-at="2022-05-09T13:23:53 PDT" name="StacksTest" finished-at="2022-05-09T13:24:00 PDT" duration-ms="7040" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- StacksTest -->
      </class> <!-- com.DsAlgoProject.TestCases.TC05_Stacks -->
      <class name="com.DsAlgoProject.TestCases.TC02_SignIn">
        <test-method signature="SignInTest(java.lang.String,java.lang.String)[pri:0, instance:com.DsAlgoProject.TestCases.TC02_SignIn@2def7a7a]" started-at="2022-05-09T13:23:28 PDT" name="SignInTest" data-provider="loginData" finished-at="2022-05-09T13:23:30 PDT" duration-ms="2740" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Neeshuindia]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Neeshu1234]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SignInTest -->
        <test-method signature="SignInTest(java.lang.String,java.lang.String)[pri:0, instance:com.DsAlgoProject.TestCases.TC02_SignIn@2def7a7a]" started-at="2022-05-09T13:23:30 PDT" name="SignInTest" data-provider="loginData" finished-at="2022-05-09T13:23:33 PDT" duration-ms="2204" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[neeshu]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Neeshu1234]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [NumpyNinja] but found [Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [NumpyNinja] but found [Login]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.DsAlgoProject.TestCases.TC02_SignIn.SignInTest(TC02_SignIn.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SignInTest -->
      </class> <!-- com.DsAlgoProject.TestCases.TC02_SignIn -->
      <class name="com.DsAlgoProject.TestCases.TC03_DataStructures">
        <test-method signature="DataStructuresTest()[pri:0, instance:com.DsAlgoProject.TestCases.TC03_DataStructures@4af70944]" started-at="2022-05-09T13:23:34 PDT" name="DataStructuresTest" finished-at="2022-05-09T13:23:39 PDT" duration-ms="5552" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DataStructuresTest -->
      </class> <!-- com.DsAlgoProject.TestCases.TC03_DataStructures -->
      <class name="com.DsAlgoProject.TestCases.TC01_Registration">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.DsAlgoProject.TestCases.TC01_Registration@124ac145]" started-at="2022-05-09T13:23:18 PDT" name="setup" finished-at="2022-05-09T13:23:23 PDT" duration-ms="4474" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Registration(java.lang.String,java.lang.String)[pri:0, instance:com.DsAlgoProject.TestCases.TC01_Registration@124ac145]" started-at="2022-05-09T13:23:23 PDT" name="Registration" data-provider="loginData" finished-at="2022-05-09T13:23:24 PDT" duration-ms="1340" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Neeshuindia]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Neeshu1234]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [NumpyNinja] but found [Registration]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [NumpyNinja] but found [Registration]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.DsAlgoProject.TestCases.TC01_Registration.Registration(TC01_Registration.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Registration -->
        <test-method signature="Registration(java.lang.String,java.lang.String)[pri:0, instance:com.DsAlgoProject.TestCases.TC01_Registration@124ac145]" started-at="2022-05-09T13:23:26 PDT" name="Registration" data-provider="loginData" finished-at="2022-05-09T13:23:27 PDT" duration-ms="1071" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[neeshu]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Neeshu1234]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [NumpyNinja] but found [Registration]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [NumpyNinja] but found [Registration]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.DsAlgoProject.TestCases.TC01_Registration.Registration(TC01_Registration.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Registration -->
        <test-method is-config="true" signature="tearDown(java.lang.String)[pri:0, instance:com.DsAlgoProject.TestCases.TC01_Registration@124ac145]" started-at="2022-05-09T13:24:00 PDT" name="tearDown" finished-at="2022-05-09T13:24:01 PDT" duration-ms="718" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.DsAlgoProject.TestCases.TC01_Registration -->
      <class name="com.DsAlgoProject.TestCases.TC04_Arrays">
        <test-method signature="ArraysTest()[pri:0, instance:com.DsAlgoProject.TestCases.TC04_Arrays@35267fd4]" started-at="2022-05-09T13:23:39 PDT" name="ArraysTest" finished-at="2022-05-09T13:23:53 PDT" duration-ms="13967" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArraysTest -->
      </class> <!-- com.DsAlgoProject.TestCases.TC04_Arrays -->
    </test> <!-- TestonEdge -->
  </suite> <!-- Suite -->
</testng-results>
